# Generated by Django 5.1 on 2024-09-26 16:35

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_payment_stripe_payment_url_payment_stripe_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Сумма",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="stripe_payment_url",
            field=models.URLField(
                default="http://127.0.0.1/",
                help_text="URL оплаты Stripe",
                verbose_name="URL оплаты Stripe",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="payment",
            name="stripe_session_id",
            field=models.CharField(
                default="12321321",
                help_text="ID сессии Stripe",
                max_length=150,
                verbose_name="ID сессии Stripe",
            ),
            preserve_default=False,
        ),
    ]
