# Generated by Django 5.1 on 2024-09-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_payment_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="stripe_payment_url",
            field=models.URLField(
                help_text="URL оплаты Stripe",
                max_length=250,
                verbose_name="URL оплаты Stripe",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="stripe_session_id",
            field=models.CharField(
                help_text="ID сессии Stripe",
                max_length=250,
                verbose_name="ID сессии Stripe",
            ),
        ),
    ]
