# Generated by Django 5.1 on 2024-09-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_payment_stripe_payment_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="stripe_payment_url",
            field=models.URLField(
                help_text="URL оплаты Stripe",
                max_length=500,
                verbose_name="URL оплаты Stripe",
            ),
        ),
    ]
