# Generated by Django 5.1 on 2024-09-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_payment_stripe_payment_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="stripe_payment_status",
            field=models.CharField(
                blank=True,
                help_text="Статус платежа в Stripe",
                max_length=50,
                null=True,
                verbose_name="Статус оплаты",
            ),
        ),
    ]
