# Generated by Django 5.1 on 2024-09-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_payment_stripe_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="stripe_payment_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("no_payment_required", "Не требуется оплата"),
                    ("paid", "Оплачено"),
                    ("unpaid", "Не оплачено"),
                ],
                help_text="Статус платежа в Stripe",
                max_length=50,
                null=True,
                verbose_name="Статус оплаты",
            ),
        ),
    ]
