# Generated by Django 5.1 on 2024-09-16 15:07

import materials.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_course_owner_lesson_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="video",
            field=models.URLField(
                help_text="Введите ссылку на видео урока",
                validators=[materials.validators.validate_admin_youtube_link],
                verbose_name="Видео урока",
            ),
        ),
    ]
