# Generated by Django 5.1 on 2024-09-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_alter_lesson_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=20000,
                help_text="Введите цену курса",
                max_digits=10,
                verbose_name="Цена",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="stripe_product_id",
            field=models.CharField(
                blank=True,
                help_text="ID продукта Stripe",
                max_length=150,
                null=True,
                verbose_name="ID продукта Stripe",
            ),
        ),
    ]
