# Generated by Django 5.1 on 2024-09-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_course_price_course_stripe_product_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="last_update",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Дата последнего обновления курса",
                verbose_name="Дата последнего обновления",
            ),
        ),
    ]
